name: Each Test - Separate Job
on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
        browser:
          description: 'Browser'
          required: true
          default: 'chromium'
          type: choice
          options:
            - chromium
            - firefox
            - webkit
        tags:
          description: 'Run tests with Tags'
          required: false
          type: string

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  test:
    name: Run ${{ matrix.name }}
    runs-on: ubuntu-latest

    env:
      PRODUCTS_LIST_ENDPOINT: ${{ secrets.PRODUCTS_LIST_ENDPOINT }}
      BRANDS_LIST_ENDPOINT: ${{ secrets.BRANDS_LIST_ENDPOINT }}
      VERIFY_LOGIN_ENDPOINT: ${{ secrets.VERIFY_LOGIN_ENDPOINT }}
      BASE_URL: ${{ secrets.BASE_URL }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - name: TC-1
            spec: tests/TC-1/signUp.spec.ts
          - name: TC-12
            spec: tests/TC-12/addProductsIntoCart.spec.ts
          - name: API
            spec: tests/API/API.spec.ts

    steps:
          - uses: actions/checkout@v4

          - uses: actions/setup-node@v4
            with:
              node-version: 24

          - name: Cache node modules
            uses: actions/cache@v4
            with:
              path: node_modules
              key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
              restore-keys: |
                ${{ runner.os }}-node-

          - name: Cache Playwright browsers
            uses: actions/cache@v4
            with:
              path: ~/.cache/ms-playwright
              key: ${{ runner.os }}-playwright-${{ hashFiles('package-lock.json') }}
              restore-keys: |
                ${{ runner.os }}-playwright-

          - run: npm ci

          - run: npx playwright install --with-deps

          - name: Run tests
            run: npx playwright test ${{ matrix.spec }} --grep "${{ github.event.inputs.grep }}" --project=chromium
            env:
              TESTOMATIO: ${{ secrets.TESTOMATIO}}                   # API key
              TESTOMATIO_RUN: ${{ github.event.inputs.run }}          # optional run ID
              TESTOMATIO_URL: ${{ github.event.inputs.testomatio_url }} # optional custom URL


         