name: Single Job Strategy
on:
  push:
    branches: [SingleJob]
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  test:
    name: It is a job name from the 12th row
    runs-on: ubuntu-latest

    env:
      PRODUCTS_LIST_ENDPOINT: ${{ secrets.PRODUCTS_LIST_ENDPOINT }}
      BRANDS_LIST_ENDPOINT: ${{ secrets.BRANDS_LIST_ENDPOINT }}
      VERIFY_LOGIN_ENDPOINT: ${{ secrets.VERIFY_LOGIN_ENDPOINT }}
      BASE_URL: ${{ secrets.BASE_URL }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 24

      - run: npm ci

      - run: npx playwright install --with-deps

      - name: Monkey name for human
        run: npx playwright test
        env:
          TESTOMATIO: ${{ secrets.TESTOMATIO }}
          TESTOMATIO_RUN: ${{ github.event.inputs.run }}
          TESTOMATIO_URL: ${{ github.event.inputs.testomatio_url }}